kinematics:
  joint1:
    x: 0
    y: 0
    z: 0.173
    roll: 0
    pitch: 0
    yaw: 0
  joint2:
    x: 0
    y: -0.086
    z: 0
    roll: 0
    pitch: -1.5708
    yaw: 1.5708
  joint3:
    x: 0.13635
    y: 0
    z: -0.086
    roll: 0
    pitch: 0
    yaw: 0
  joint4:
    x: 0.1195
    y: 0
    z: 0.082
    roll: 0
    pitch: 0
    yaw: 1.5708
  joint5:
    x: 0
    y: -0.09415
    z: 0
    roll: 1.5708
    pitch: 0
    yaw: 0
  joint6:
    x: 0
    y: 0.055
    z: 0
    roll: -1.5708
    pitch: 0
    yaw: 0
  hash: default_values_no_calib
